# -*- coding: utf-8 -*-
"""kaggle_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CaK6U4dnZ3FZ-SwrKJAmtOWm9qu-geSG

## 搭建环境
"""

!python --version

# !pip install update

!pip uninstall torch torchvision torchaudio -y

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

!pip install ultralytics

!git clone https://github.com/gitaeron/traffic_sign_dataset_in_yolo_format.git

# !cd /kaggle/working/traffic_sign_dataset_in_yolo_format/

!ls -ailF /kaggle/working/traffic_sign_dataset_in_yolo_format/

"""## 处理数据集"""

!mkdir /kaggle/working/traffic_sign_dataset_in_yolo_format/data

!cp -r /kaggle/working/traffic_sign_dataset_in_yolo_format/straight_only/*      /kaggle/working/traffic_sign_dataset_in_yolo_format/data/
!cp -r /kaggle/working/traffic_sign_dataset_in_yolo_format/turn_left/*   /kaggle/working/traffic_sign_dataset_in_yolo_format/data/
!cp -r /kaggle/working/traffic_sign_dataset_in_yolo_format/turn_right/*  /kaggle/working/traffic_sign_dataset_in_yolo_format/data/

!ls /kaggle/working/traffic_sign_dataset_in_yolo_format/data/

!cat /kaggle/working/traffic_sign_dataset_in_yolo_format/data/classes.txt

!cat /kaggle/working/traffic_sign_dataset_in_yolo_format/dataset.yaml

!echo "straight_only: "
!ls -l /kaggle/working/traffic_sign_dataset_in_yolo_format/straight_only/images/train/ | grep "^-" | wc -l
!echo "turn_left: "
!ls -l /kaggle/working/traffic_sign_dataset_in_yolo_format/turn_left/images/train/ | grep "^-" | wc -l
!echo "turn_right: "
!ls -l /kaggle/working/traffic_sign_dataset_in_yolo_format/turn_right/images/train/  | grep "^-" | wc -l

!echo "data img: "
!ls -l /kaggle/working/traffic_sign_dataset_in_yolo_format/data/images/train/  | grep "^-" | wc -l
!echo "data label: "
!ls -l /kaggle/working/traffic_sign_dataset_in_yolo_format/data/labels/train/  | grep "^-" | wc -l

with open("/kaggle/working/traffic_sign_dataset_in_yolo_format/data/dataset.yaml", 'w+', encoding='utf-8') as fp:
    fp.write("path: /kaggle/working/traffic_sign_dataset_in_yolo_format/data\n")
    fp.write("train: # train images (relative to 'path')  16551 images\n")
    fp.write("  - images/train\n")
    fp.write("val: # val images (relative to 'path')  4952 images\n")
    fp.write("  - images/val\n")
    fp.write("test: # test images (optional)\n")
    fp.write("  - predict\n")
    fp.write("nc: 3\n")
    fp.write("# Classes \n")
    fp.write("names: ['straight_only', 'turn_left', 'turn_right']")

!cat /kaggle/working/traffic_sign_dataset_in_yolo_format/data/dataset.yaml

"""## 训练"""

# only error in kaggle
!pip uninstall wandb -y

# !nvidia-smi

import torch
import torchvision

print(torchvision.__version__)
print(torch.__version__)

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_name(1))
print(torch.cuda.current_device())

!yolo detect train data=/kaggle/working/traffic_sign_dataset_in_yolo_format/data/dataset.yaml model=yolov8n.pt  batch=64 epochs=25 imgsz=640 save=True

"""## 保存训练结果"""

!sudo apt-get install rar

!ls /kaggle/working/runs/detect/

!rar a train2.rar /kaggle/working/runs/detect/train/*
!ls

import os
os.chdir(r'/kaggle/working/')

from IPython.display import FileLink

FileLink(r'train.rar')

"""## 预测"""

# !yolo detect predict model=/content/runs/detect/train/weights/best.pt source=/content/predict save=True

"""## 防止挂断"""

!yolo detect train data=/kaggle/working/traffic_sign_dataset_in_yolo_format/data/dataset.yaml model=yolov8n.pt  batch=64 epochs=25 imgsz=640 save=True

