# -*- coding: utf-8 -*-
"""my_train

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yeLhq44-w95SdBlaZb6GwBjQmmChRoUm

## 搭建环境
"""

!python --version

!pip install update

!pip install ultralytics

!pwd

!git clone https://github.com/gitaeron/traffic_sign_dataset_in_yolo_format.git

!ls -ailF

"""## 查看机器配置"""

!nvidia-smi

!cat /proc/cpuinfo

"""## 处理数据集"""

!ls -ailF /content/traffic_sign_dataset_in_yolo_format/

!mkdir /content/traffic_sign_dataset_in_yolo_format/data

!cp -r /content/traffic_sign_dataset_in_yolo_format/straight_only/*  /content/traffic_sign_dataset_in_yolo_format/data/
!cp -r /content/traffic_sign_dataset_in_yolo_format/turn_left/* /content/traffic_sign_dataset_in_yolo_format/data/
!cp -r /content/traffic_sign_dataset_in_yolo_format/turn_right/* /content/traffic_sign_dataset_in_yolo_format/data/

!echo "straight_only: "
!ls -l /content/traffic_sign_dataset_in_yolo_format/straight_only/images/train/ | grep "^-" | wc -l

!echo "turn_left: "
!ls -l /content/traffic_sign_dataset_in_yolo_format/turn_left/images/train/  | grep "^-" | wc -l

!echo "turn_right: "
!ls -l /content/traffic_sign_dataset_in_yolo_format/turn_right/images/train/  | grep "^-" | wc -l

!echo "data: "
!ls -l /content/traffic_sign_dataset_in_yolo_format/data/images/train/  | grep "^-" | wc -l
!ls -l /content/traffic_sign_dataset_in_yolo_format/data/images/val/  | grep "^-" | wc -l

!cp -r /content/traffic_sign_dataset_in_yolo_format/mix/* /content/traffic_sign_dataset_in_yolo_format/data/

!echo "data: "
!ls -l /content/traffic_sign_dataset_in_yolo_format/data/images/train/  | grep "^-" | wc -l
!ls -l /content/traffic_sign_dataset_in_yolo_format/data/images/val/  | grep "^-" | wc -l

# !rm -rf /content/traffic_sign_dataset_in_yolo_format/data

"""## 训练"""

!cat /content/dataset.yaml

!yolo detect train data=/content/dataset.yaml model=yolov8n.pt  batch=32 epochs=50 imgsz=800 save=True

"""## 预测"""

# !yolo detect predict model=/content/runs/detect/train/weights/best.pt source=/content/predict save=True

"""## 防挂断"""

!yolo detect train data=/content/dataset.yaml model=yolov8n.pt  batch=32 epochs=50 imgsz=800 save=True

